export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const CLEAR_PROFILE = 'CLEAR_PROFILE'
