export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const ACCOUNT_DELETED = 'DELETE_ACCOUNT'

export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const POST_ERROR = 'GET_POSTS_FAILURE'
export const POST_DELETED = 'POST_DELETED'
export const ADD_POST = 'ADD_POST'

export const UPDATE_LIKES = 'UPDATE_LIKES'
