export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'
